In [781]:
import pandas as pd
import numpy as np

df_90 = pd.read_csv(r"C:\Users\RuchirTyagi\f_90_days.csv")
df_90.head()

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI

In [782]:
og_df = pd.read_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\final_table_v4.xlsx')
og_df.head()

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,icd_code,...,lag_fill_date_flag,days_supply_final_flag,quantity_final_flag,rx_written_date,fill_date,ship_date,date_prescription_written,payor_name_final_flag,payor_type_final_flag,pbm_final_flag
0,1003101056,9279339279,MA,F,64,9MZ6V2LE,F,64,MA,C719,...,1,1,1,"[Timestamp('2025-08-05 00:00:00'), Timestamp('...","[Timestamp('2025-08-21 00:00:00'), Timestamp('...","[Timestamp('2025-08-22 00:00:00'), Timestamp('...","[Timestamp('2025-08-05 00:00:00'), Timestamp('...",0,0,0
1,1003101056,9279339279,MA,F,64,0XSZNET0,F,63,MA,C719,...,-1,-1,-1,"[Timestamp('2025-08-05 00:00:00'), Timestamp('...",[],"[Timestamp('2025-08-22 00:00:00'), Timestamp('...",[],0,0,0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,C719,...,-1,-1,-1,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0,0,0
3,1003221896,5280135280,WI,M,5,Y57KB31F,M,4,WI,C719,...,-1,-1,-1,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0,0,0
4,1003221896,5280135280,WI,M,5,2XJVDDQ4,M,4,WI,C719,...,-1,-1,-1,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0,0,0

In [783]:
og_df.columns

Index(['sp_prescriber_npi', 'sp_patient_id', 'sp_state', 'sp_gender', 'sp_age',
       'matched_patient_id', 'matched_gender', 'matched_age_2025',
       'matched_state', 'icd_code', 'icd_code_claims', 'parent_diag_code_flag',
       'exact_diag_code_flag', 'diag_freq', '90_days_lookback_freq',
       '180_days_lookback_freq', '360_days_lookback_freq',
       'first_last_claim_lookback', 'radiation_flag', 'radiation_freq',
       'chemotherapy_flag', 'chemotherapy_freq', 'surgery_flag',
       'surgery_freq', 'testing_flag', 'testing_freq', 'prior_treatment_flag',
       'rx_date_match_flag', 'exact_fill_date_flag', 'lag_fill_date_flag',
       'days_supply_final_flag', 'quantity_final_flag', 'rx_written_date',
       'fill_date', 'ship_date', 'date_prescription_written',
       'payor_name_final_flag', 'payor_type_final_flag', 'pbm_final_flag'],
      dtype='object')

In [784]:
df_90 = pd.merge(df_90, og_df, how='left', left_on=df_90.columns.to_list(), right_on=df_90.columns.to_list())
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,icd_code,...,lag_fill_date_flag,days_supply_final_flag,quantity_final_flag,rx_written_date,fill_date,ship_date,date_prescription_written,payor_name_final_flag,payor_type_final_flag,pbm_final_flag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,NaN,...,-1.0,-1.0,-1.0,"[Timestamp('2025-07-30 00:00:00'), Timestamp('...",[],"[Timestamp('2025-08-25 00:00:00'), Timestamp('...",[],0.0,0.0,0.0
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,C719,...,-1.0,-1.0,-1.0,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0.0,0.0,0.0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,C719,...,-1.0,-1.0,-1.0,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0.0,0.0,0.0
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,C719,...,-1.0,-1.0,-1.0,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0.0,0.0,0.0
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,C719,...,-1.0,-1.0,-1.0,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,NaN,...,-1.0,-1.0,-1.0,[Timestamp('2025-10-15 00:00:00')],[],"[Timestamp('2025-10-21 00:00:00'), Timestamp('...",[],0.0,0.0,0.0
1050,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,NaN,...,-1.0,-1.0,-1.0,[Timestamp('2025-10-15 00:00:00')],[],"[Timestamp('2025-10-21 00:00:00'), Timestamp('...",[],0.0,0.0,0.0
1051,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,NaN,...,-1.0,-1.0,-1.0,[Timestamp('2025-10-15 00:00:00')],[],"[Timestamp('2025-10-21 00:00:00'), Timestamp('...",[],0.0,0.0,0.0
1052,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,C719,...,-1.0,-1.0,-1.0,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],0.0,0.0,0.0
1053,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,C719,...,-1.0,-1.0,-1.0,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],0.0,0.0,0.0

In [785]:
columns_required = [
    'sp_prescriber_npi',
    'sp_patient_id',
    'sp_state',
    'sp_gender',
    'sp_age',
    'matched_patient_id',
    'matched_gender',
    'matched_age_2025',
    'matched_state',    
    'parent_diag_code_flag',
    'exact_diag_code_flag',
    'prior_treatment_flag',
    'rx_date_match_flag',
    'exact_fill_date_flag',
    'lag_fill_date_flag',
    'payor_name_final_flag',
    'payor_type_final_flag',
    'pbm_final_flag'
]

In [786]:
df_90 = df_90[columns_required]
df_90 = df_90.drop_duplicates(subset=['sp_patient_id', 'matched_patient_id'], keep='first').reset_index(drop=True)
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,exact_diag_code_flag,prior_treatment_flag,rx_date_match_flag,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,0.0,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,1.0,1.0,0.0,-1.0,-1.0,0.0,0.0,0.0
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,1.0,1.0,0.0,-1.0,-1.0,0.0,0.0,0.0
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,1.0,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,1.0,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0

In [787]:
def generate_confidence_score(row):
    parent_diag_code_flag = row['parent_diag_code_flag']
    exact_diag_code_flag = row['exact_diag_code_flag']
    prior_treatment_flag = row['prior_treatment_flag']
    rx_date_match_flag = row['rx_date_match_flag']
    lag_fill_date_flag = row['lag_fill_date_flag']
    payor_name_final_flag = row['payor_name_final_flag']
    payor_type_final_flag = row['payor_type_final_flag']
    pbm_final_flag = row['pbm_final_flag']

    diagnosis_score_parent = 0
    diagnosis_score_exact = 0

    if parent_diag_code_flag == 1:
        diagnosis_score_parent = 5
    
    if exact_diag_code_flag == 1:
        diagnosis_score_exact = 5

    final_dispense = 0

    if rx_date_match_flag == 1:
        if lag_fill_date_flag == 1 or lag_fill_date_flag == -1:
            final_dispense = 20

    therapy_score = 0

    if prior_treatment_flag == 1:
        therapy_score = 10

    payor_type_score = 0
    payor_name_score = 0
    pbm_score = 0

    if payor_name_final_flag == 1:
        payor_name_score = 2

    if payor_type_final_flag == 1:
        payor_type_score = 5 

    if pbm_final_flag == 1:
        pbm_score = 3

    confidence_score = diagnosis_score_parent + diagnosis_score_exact + final_dispense + therapy_score + payor_type_score + payor_name_score + pbm_score + 50

    return confidence_score

In [788]:
df_90['confidence_score'] = df_90.apply(
    generate_confidence_score,
    axis=1
)

df_90.head()

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,exact_diag_code_flag,prior_treatment_flag,rx_date_match_flag,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,0.0,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,55
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,1.0,1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,70
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,1.0,1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,70
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,1.0,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,60

In [789]:
df_90.to_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\df_90_with_confidence_score_v1.xlsx', index=False)

In [790]:
print("Unique SP patients with confidence score >= 80:", len(df_90[df_90['confidence_score'] >= 90]['sp_patient_id'].unique()))
print("Unique SP patients with confidence score >= 70 and <= 79:", len(df_90[(df_90['confidence_score'] >= 70) & (df_90['confidence_score'] <= 79)]['sp_patient_id'].unique()))
print("Unique SP patients with confidence score >= 60 and <= 69:", len(df_90[(df_90['confidence_score'] >= 60) & (df_90['confidence_score'] <= 69)]['sp_patient_id'].unique()))
print("Unique SP patients with confidence score >= 50 and <= 59:", len(df_90[(df_90['confidence_score'] >= 50) & (df_90['confidence_score'] <= 59)]['sp_patient_id'].unique()))
print("Unique SP patients with confidence score >= 40 and <= 49:", len(df_90[(df_90['confidence_score'] >= 40) & (df_90['confidence_score'] <= 49)]['sp_patient_id'].unique()))
print("Unique SP patients with confidence score < 40:", len(df_90[df_90['confidence_score'] < 40]['sp_patient_id'].unique()))

Unique SP patients with confidence score >= 80: 4
Unique SP patients with confidence score >= 70 and <= 79: 50
Unique SP patients with confidence score >= 60 and <= 69: 180
Unique SP patients with confidence score >= 50 and <= 59: 161
Unique SP patients with confidence score >= 40 and <= 49: 0
Unique SP patients with confidence score < 40: 0

In [791]:
sp_data = pd.read_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\SP Data Load.xlsx')

In [792]:
patients = df_90['sp_patient_id'].unique()
sp_df = sp_data[sp_data['patient_id'].isin(patients)][['patient_id', 'referral_date', 'primary_icd_code']]

In [793]:
sp_df = sp_df[sp_df['primary_icd_code'].str.contains('C71', na=False)]

In [794]:
df_90 = pd.merge(df_90, sp_df,how='left', left_on='sp_patient_id', right_on='patient_id')

In [795]:
df_90 = df_90.drop(columns=['patient_id'], axis=1)
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,prior_treatment_flag,rx_date_match_flag,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,primary_icd_code
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaN
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,55,2025-09-02,C71.9
2,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,55,2025-09-02,C71.9
3,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,55,2025-09-02,C71.9
4,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,55,2025-09-02,C71.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7216,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,2025-09-03,C71.9
7217,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,2025-09-03,C71.9
7218,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,2025-09-03,C71.9
7219,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,2025-09-03,C71.9
7220,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,2025-09-03,C71.9

In [796]:
df_90 = df_90.drop_duplicates(subset=['sp_prescriber_npi', 'sp_patient_id', 'matched_patient_id'], keep='first').reset_index(drop=True)
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,prior_treatment_flag,rx_date_match_flag,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,primary_icd_code
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaN
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,55,2025-09-02,C71.9
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,C71.9
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,C71.9
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-02,C71.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaN
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaN
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaN
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-03,C71.9
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,2025-09-03,C71.9

In [797]:
df_90 = df_90.drop(columns=['primary_icd_code'], axis=1)

In [798]:
mx = pd.read_csv(r'C:\Users\RuchirTyagi\mx_data_v4.csv')
mx

      patient_id service_date
0       317ZTK26   2025-04-30
1       RCCC0303   2025-04-30
2       0DSBGP66   2025-04-30
3       STXZ0CZK   2025-04-30
4       EDYSK4DC   2025-04-30
...          ...          ...
48817   9QMRCJ6R   2025-10-05
48818   87WR4LQ3   2025-10-05
48819   9QMRCJ6R   2025-10-05
48820   0416Q8Z9   2025-10-06
48821   0416Q8Z9   2025-10-06

[48822 rows x 2 columns]

In [799]:
df_90 = pd.merge(df_90, mx, how='left', left_on='matched_patient_id', right_on='patient_id').drop(columns=['patient_id'], axis=1)
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,prior_treatment_flag,rx_date_match_flag,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaN
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,55,2025-09-02,NaN
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20
3,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20
4,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40719,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-09-24
40720,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-09-24
40721,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-09-24
40722,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-09-24
40723,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,50,2025-09-03,NaN

In [800]:
df_90['service_date'] = pd.to_datetime(df_90['service_date'], errors='coerce')

In [801]:
def calculate_days_between_dates(row):
    referral_date = row['referral_date']
    service_date = row['service_date']

    if pd.isna(referral_date) or pd.isna(service_date):
        return np.inf
    
    days_difference = (service_date - referral_date).days

    return abs(days_difference)

In [802]:
df_90['diagnosis_days_lag'] = df_90.apply(
    calculate_days_between_dates,
    axis=1
)

In [803]:
df_90_temp = df_90.loc[
    df_90.groupby(['sp_patient_id', 'matched_patient_id'])['diagnosis_days_lag'].idxmin()
].reset_index(drop=True)

df_90_temp

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,rx_date_match_flag,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag
0,1841225620,179530179,MA,M,6,6RE9BESR,M,7,MA,1.0,...,0.0,-1.0,-1.0,0.0,0.0,1.0,63,2025-08-12,2025-08-12,0.0
1,1891827465,180030180,FL,F,71,55TTYKZ7,F,72,FL,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,1.0,53,NaT,NaT,inf
2,1891827465,180030180,FL,F,71,GD6VNS7R,F,72,FL,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-05-23,inf
3,1891827465,180030180,FL,F,71,H55BHB5H,F,71,FL,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf
4,1891827465,180030180,FL,F,71,JR6TRYD9,F,72,FL,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,1.0,53,NaT,NaT,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1508066309,9981259981,AZ,F,9,LZK03503,F,9,AZ,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-05-13,inf
904,1508066309,9981259981,AZ,F,9,T7SG3D9L,F,9,AZ,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf
905,1508066309,9981259981,AZ,F,9,W51DCS3P,F,9,AZ,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf
906,1508066309,9981259981,AZ,F,9,ZWL192QP,F,8,AZ,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-05-14,inf
907,1861802837,9982209982,MN,F,22,G0MFRD1N,F,22,MN,1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-11-06,2025-09-15,52.0

In [804]:
df_90.to_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\df_90_with_confidence_score_diag_lag_v2.xlsx')

In [805]:
df_90 = df_90.drop_duplicates(subset=['sp_patient_id', 'matched_patient_id'], keep='first').reset_index(drop=True)
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,rx_date_match_flag,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,55,2025-09-02,NaT,inf
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20,105.0
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-15,110.0
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-02,NaT,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-06-11,84.0
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,2025-09-03,NaT,inf

In [806]:
df_90.columns

Index(['sp_prescriber_npi', 'sp_patient_id', 'sp_state', 'sp_gender', 'sp_age',
       'matched_patient_id', 'matched_gender', 'matched_age_2025',
       'matched_state', 'parent_diag_code_flag', 'exact_diag_code_flag',
       'prior_treatment_flag', 'rx_date_match_flag', 'exact_fill_date_flag',
       'lag_fill_date_flag', 'payor_name_final_flag', 'payor_type_final_flag',
       'pbm_final_flag', 'confidence_score', 'referral_date', 'service_date',
       'diagnosis_days_lag'],
      dtype='object')

In [807]:
df_90.sort_values(by='sp_patient_id', ascending=True)

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,rx_date_match_flag,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag
763,1841225620,179530179,MA,M,6,6RE9BESR,M,7,MA,1.0,...,0.0,-1.0,-1.0,0.0,0.0,1.0,63,2025-08-12,2025-04-30,104.0
829,1891827465,180030180,FL,F,71,ZXK377VD,F,70,FL,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,1.0,53,NaT,NaT,inf
827,1891827465,180030180,FL,F,71,QT4PX6DP,F,70,FL,-1.0,...,0.0,-1.0,-1.0,1.0,0.0,1.0,55,NaT,2025-05-18,inf
828,1891827465,180030180,FL,F,71,ZQ7Y6T35,F,70,FL,-1.0,...,0.0,-1.0,-1.0,1.0,0.0,1.0,55,NaT,2025-05-16,inf
826,1891827465,180030180,FL,F,71,KF1RCS7Q,F,72,FL,-1.0,...,1.0,-1.0,-1.0,0.0,0.0,0.0,70,NaT,2025-05-05,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,1508066309,9981259981,AZ,F,9,KMPJ2EWB,F,9,AZ,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-08-13,inf
434,1508066309,9981259981,AZ,F,9,4C2CQ9MH,F,9,AZ,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-07-22,inf
436,1508066309,9981259981,AZ,F,9,DM5YNS4D,F,8,AZ,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf
441,1508066309,9981259981,AZ,F,9,ZWL192QP,F,8,AZ,-1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-05-14,inf
789,1861802837,9982209982,MN,F,22,G0MFRD1N,F,22,MN,1.0,...,0.0,-1.0,-1.0,0.0,0.0,0.0,60,2025-11-06,2025-04-30,190.0

In [812]:
df_90["best_match_flag"] = 0

def flag_best(group):
    # Step 1: max confidence rows
    max_conf = group["confidence_score"].max()
    g = group[group["confidence_score"] == max_conf]

    # If max confidence is unique, assign 1 directly
    if len(g) == 1:
        return g.index

    # Step 2: max confidence is tied, use diagnosis_days_lag
    # If all tied rows have inf lag, none should get 1
    if np.isinf(g["diagnosis_days_lag"]).all():
        return pd.Index([])

    # Exclude inf while finding minimum lag
    valid_lag = g[~np.isinf(g["diagnosis_days_lag"])]

    # If somehow no valid lag remains, none gets 1
    if valid_lag.empty:
        return pd.Index([])

    # Minimum lag among tied max-confidence rows
    min_lag = valid_lag["diagnosis_days_lag"].min()

    # All rows with that minimum lag get 1
    return g[g["diagnosis_days_lag"] == min_lag].index


best_indices = (
    df_90.groupby("sp_patient_id", group_keys=False)
         .apply(flag_best)
         .explode()
         .dropna()
         .astype(int)
)

df_90.loc[best_indices, "best_match_flag"] = 1

C:\Users\RuchirTyagi\AppData\Local\Temp\ipykernel_17896\311702394.py:33: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(flag_best)

In [814]:
df_90[df_90['sp_patient_id'] == 5280135280]

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,best_match_flag
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,55,2025-09-02,NaT,inf,0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20,105.0,0
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-15,110.0,0
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-02,NaT,inf,0
5,1003221896,5280135280,WI,M,5,Y57KB31F,M,4,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-04-30,125.0,0
269,1306225008,5280135280,WI,M,5,2XJVDDQ4,M,4,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-06-05,89.0,1
270,1306225008,5280135280,WI,M,5,K6F38TL3,M,5,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,65,2025-09-02,2025-04-30,125.0,0

In [811]:
df_90[df_90['best_match_flag']==1]

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,best_match_flag
6,1003349028,7880807880,IL,F,23,0YSEZ8KH,F,23,IL,1.0,...,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-23,2025-04-30,146.0,1
7,1003349028,8781638781,IL,F,24,0YSEZ8KH,F,23,IL,1.0,...,-1.0,-1.0,0.0,0.0,0.0,60,2025-10-20,2025-04-30,173.0,1
8,1003606146,3582653582,WA,M,23,K7V9CEZ9,M,23,WA,1.0,...,-1.0,-1.0,0.0,0.0,0.0,60,2025-11-19,2025-07-29,113.0,1
9,1003606146,5779975779,HI,M,6,MZT62X02,M,7,HI,1.0,...,-1.0,-1.0,0.0,0.0,1.0,83,2025-08-26,2025-04-30,118.0,1
11,1023215944,880080880,VA,M,9,8H1K9G8Y,M,9,VA,1.0,...,-1.0,-1.0,0.0,0.0,0.0,55,2025-08-28,2025-07-16,43.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1962784298,5379465379,OR,F,30,HPP34R4H,F,29,OR,1.0,...,-1.0,-1.0,0.0,0.0,0.0,55,2025-08-11,2025-04-30,103.0,1
884,1972547560,3680363680,VA,M,16,WW6H7EV9,M,16,VA,1.0,...,0.0,1.0,0.0,0.0,1.0,78,2025-09-09,2025-05-19,113.0,1
886,1972776623,3180333180,CA,M,28,YWX6W4NW,M,29,CA,1.0,...,0.0,1.0,0.0,0.0,0.0,80,2025-09-08,NaT,inf,1
887,1982686622,2282122282,CT,M,22,KJP330PF,M,22,CT,1.0,...,-1.0,-1.0,0.0,1.0,1.0,68,2025-11-04,2025-07-28,99.0,1
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-06-11,84.0,1

In [815]:
df_90.to_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\df_90_with_best_match_flag.xlsx', index=False)

In [ ]:
max_service_date_df = pd.read_csv(r'C:\Users\RuchirTyagi\max_service_date_v2.csv')
max_service_date_df

       prescriber_npi patient_id latest_service_date
0        1.003003e+09   53R57JZW          2024-10-27
1        1.003005e+09   LWV2GH78          2023-12-26
2        1.003006e+09   BSZNCHZ1          2023-08-28
3        1.003006e+09   BVEF6YRE          2024-01-31
4        1.003010e+09   XGL43H7F          2023-07-09
...               ...        ...                 ...
56867             NaN   ZXK377VD          2025-09-24
56868             NaN   ZY23WCRV          2025-08-26
56869             NaN   ZY5D59E2          2025-09-09
56870             NaN   ZZ0JVC79          2025-09-04
56871             NaN   ZZEGLZG6          2025-09-30

[56872 rows x 3 columns]

In [ ]:
max_service_date_df.dropna(inplace=True)
max_service_date_df

       prescriber_npi patient_id latest_service_date
0        1.003003e+09   53R57JZW          2024-10-27
1        1.003005e+09   LWV2GH78          2023-12-26
2        1.003006e+09   BSZNCHZ1          2023-08-28
3        1.003006e+09   BVEF6YRE          2024-01-31
4        1.003010e+09   XGL43H7F          2023-07-09
...               ...        ...                 ...
55107    1.992995e+09   GLHTJ60L          2025-09-29
55108    1.992996e+09   FH1BS0BZ          2023-07-10
55109    1.992996e+09   BWKMDE00          2025-09-30
55110    1.992996e+09   GJQM22ZK          2025-09-25
55111    1.992998e+09   SYV851SL          2025-09-29

[55112 rows x 3 columns]

In [ ]:
df_90 = pd.merge(df_90, max_service_date_df, how='left', left_on=['sp_prescriber_npi', 'matched_patient_id'], right_on=['prescriber_npi', 'patient_id'])
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,best_match_flag,prescriber_npi,patient_id,latest_service_date
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,0.0,0.0,50,NaT,NaT,inf,1,1.003222e+09,H0S6CJSK,2025-05-13
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,0.0,0.0,55,2025-09-02,NaT,inf,0,1.003222e+09,843DX0KF,2025-06-04
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,0.0,0.0,70,2025-09-02,2025-05-20,105.0,0,1.003222e+09,88ZFPLSE,2025-09-12
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,0.0,0.0,70,2025-09-02,2025-05-15,110.0,0,1.003222e+09,H2S3566S,2025-09-09
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,0.0,0.0,60,2025-09-02,NaT,inf,0,1.003222e+09,VMDGVRH6,2025-10-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,0.0,0.0,50,NaT,2025-05-06,inf,1,1.982903e+09,KHP2NC7M,2025-08-26
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,0.0,0.0,50,NaT,NaT,inf,1,1.982903e+09,Q82R8LBC,2025-10-06
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,0.0,0.0,50,NaT,2025-05-06,inf,1,1.982903e+09,TW1WHTTM,2025-09-25
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,0.0,0.0,60,2025-09-03,2025-06-11,84.0,1,1.992402e+09,06R2J3C9,2025-09-16
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,0.0,0.0,50,2025-09-03,NaT,inf,0,1.992402e+09,H987GVYY,2025-10-03

In [ ]:
df_90 = df_90.drop(columns=['prescriber_npi', 'patient_id'], axis=1)
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,best_match_flag,latest_service_date
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,1,2025-05-13
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0.0,0.0,0.0,55,2025-09-02,NaT,inf,0,2025-06-04
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20,105.0,0,2025-09-12
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-15,110.0,0,2025-09-09
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0.0,0.0,0.0,60,2025-09-02,NaT,inf,0,2025-10-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,1,2025-08-26
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,1,2025-10-06
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,1,2025-09-25
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-06-11,84.0,1,2025-09-16
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,0.0,0.0,50,2025-09-03,NaT,inf,0,2025-10-03

In [ ]:
df_90 = df_90.drop(columns=['best_match_flag'], axis=1)

In [ ]:
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,exact_fill_date_flag,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,latest_service_date
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,2025-05-13
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,55,2025-09-02,NaT,inf,2025-06-04
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20,105.0,2025-09-12
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-15,110.0,2025-09-09
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-02,NaT,inf,2025-10-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,2025-08-26
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,2025-10-06
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,2025-09-25
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-06-11,84.0,2025-09-16
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,-1.0,0.0,0.0,0.0,50,2025-09-03,NaT,inf,2025-10-03

In [ ]:
df_90["latest_service_date"] = pd.to_datetime(df_90["latest_service_date"])

max_conf = df_90.groupby("sp_patient_id")["confidence_score"].transform("max")

latest_date_among_max_conf = df_90["latest_service_date"].where(df_90["confidence_score"] == max_conf)

max_date = latest_date_among_max_conf.groupby(df_90["sp_patient_id"]).transform("max")

df_90["best_match_flag"] = (
    (df_90["confidence_score"] == max_conf) &
    (df_90["latest_service_date"] == max_date)
).astype(int)

In [ ]:
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,latest_service_date,best_match_flag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,2025-05-13,1
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0.0,0.0,0.0,55,2025-09-02,NaT,inf,2025-06-04,0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20,105.0,2025-09-12,1
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-15,110.0,2025-09-09,0
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0.0,0.0,0.0,60,2025-09-02,NaT,inf,2025-10-03,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,2025-08-26,0
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,2025-10-06,1
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,2025-09-25,0
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-06-11,84.0,2025-09-16,1
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,0.0,0.0,50,2025-09-03,NaT,inf,2025-10-03,0

In [ ]:
df_90.to_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\df_90_with_best_match_flag_and_service_date_v2.xlsx', index=False)

In [ ]:
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,latest_service_date,best_match_flag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,2025-05-13,1
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0.0,0.0,0.0,55,2025-09-02,NaT,inf,2025-06-04,0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20,105.0,2025-09-12,1
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-15,110.0,2025-09-09,0
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0.0,0.0,0.0,60,2025-09-02,NaT,inf,2025-10-03,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,2025-08-26,0
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,2025-10-06,1
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,2025-09-25,0
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-06-11,84.0,2025-09-16,1
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,0.0,0.0,50,2025-09-03,NaT,inf,2025-10-03,0

In [ ]:
payor_df = pd.read_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\final_table_v4.xlsx')
payor_df

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,icd_code,...,lag_fill_date_flag,days_supply_final_flag,quantity_final_flag,rx_written_date,fill_date,ship_date,date_prescription_written,payor_name_final_flag,payor_type_final_flag,pbm_final_flag
0,1003101056,9279339279,MA,F,64,9MZ6V2LE,F,64,MA,C719,...,1,1,1,"[Timestamp('2025-08-05 00:00:00'), Timestamp('...","[Timestamp('2025-08-21 00:00:00'), Timestamp('...","[Timestamp('2025-08-22 00:00:00'), Timestamp('...","[Timestamp('2025-08-05 00:00:00'), Timestamp('...",0,0,0
1,1003101056,9279339279,MA,F,64,0XSZNET0,F,63,MA,C719,...,-1,-1,-1,"[Timestamp('2025-08-05 00:00:00'), Timestamp('...",[],"[Timestamp('2025-08-22 00:00:00'), Timestamp('...",[],0,0,0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,C719,...,-1,-1,-1,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0,0,0
3,1003221896,5280135280,WI,M,5,Y57KB31F,M,4,WI,C719,...,-1,-1,-1,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0,0,0
4,1003221896,5280135280,WI,M,5,2XJVDDQ4,M,4,WI,C719,...,-1,-1,-1,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2201,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,C719,...,-1,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],0,0,0
2202,1992401996,1880171880,VA,M,12,S9E2PSB7,M,13,VA,C719,...,-1,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],0,0,0
2203,1992401996,1880171880,VA,M,12,38B8371E,M,13,VA,C719,...,-1,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],0,0,0
2204,1992401996,1880171880,VA,M,12,JJSW263R,M,13,VA,C719,...,-1,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],0,0,1
2205,1992401996,1880171880,VA,M,12,H2J20RG9,M,13,VA,C719,...,-1,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],0,0,0

In [ ]:
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,latest_service_date,best_match_flag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,2025-05-13,1
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0.0,0.0,0.0,55,2025-09-02,NaT,inf,2025-06-04,0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-20,105.0,2025-09-12,1
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0.0,0.0,0.0,70,2025-09-02,2025-05-15,110.0,2025-09-09,0
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0.0,0.0,0.0,60,2025-09-02,NaT,inf,2025-10-03,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,2025-08-26,0
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,NaT,inf,2025-10-06,1
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0.0,0.0,0.0,50,NaT,2025-05-06,inf,2025-09-25,0
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0.0,0.0,0.0,60,2025-09-03,2025-06-11,84.0,2025-09-16,1
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0.0,0.0,0.0,50,2025-09-03,NaT,inf,2025-10-03,0

In [ ]:
df_90.columns

Index(['sp_prescriber_npi', 'sp_patient_id', 'sp_state', 'sp_gender', 'sp_age',
       'matched_patient_id', 'matched_gender', 'matched_age_2025',
       'matched_state', 'parent_diag_code_flag', 'exact_diag_code_flag',
       'prior_treatment_flag', 'rx_date_match_flag', 'exact_fill_date_flag',
       'lag_fill_date_flag', 'payor_name_final_flag', 'payor_type_final_flag',
       'pbm_final_flag', 'confidence_score', 'referral_date', 'service_date',
       'diagnosis_days_lag', 'latest_service_date', 'best_match_flag'],
      dtype='object')

In [ ]:
df_90['payor_name_final_flag'] = payor_df['payor_name_final_flag']
df_90['payor_type_final_flag'] = payor_df['payor_type_final_flag']
df_90['pbm_final_flag'] = payor_df['pbm_final_flag']
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,latest_service_date,best_match_flag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0,0,0,50,NaT,NaT,inf,2025-05-13,1
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0,0,0,55,2025-09-02,NaT,inf,2025-06-04,0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0,0,0,70,2025-09-02,2025-05-20,105.0,2025-09-12,1
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0,0,0,70,2025-09-02,2025-05-15,110.0,2025-09-09,0
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0,0,0,60,2025-09-02,NaT,inf,2025-10-03,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0,0,0,50,NaT,2025-05-06,inf,2025-08-26,0
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0,0,0,50,NaT,NaT,inf,2025-10-06,1
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0,0,0,50,NaT,2025-05-06,inf,2025-09-25,0
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,1,0,1,60,2025-09-03,2025-06-11,84.0,2025-09-16,1
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0,0,0,50,2025-09-03,NaT,inf,2025-10-03,0

In [ ]:
df_90.to_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\df_90_new_payor.xlsx', index=False)

In [ ]:
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date,service_date,diagnosis_days_lag,latest_service_date,best_match_flag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0,0,0,50,NaT,NaT,inf,2025-05-13,1
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0,0,0,55,2025-09-02,NaT,inf,2025-06-04,0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0,0,0,70,2025-09-02,2025-05-20,105.0,2025-09-12,1
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0,0,0,70,2025-09-02,2025-05-15,110.0,2025-09-09,0
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0,0,0,60,2025-09-02,NaT,inf,2025-10-03,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0,0,0,50,NaT,2025-05-06,inf,2025-08-26,0
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0,0,0,50,NaT,NaT,inf,2025-10-06,1
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0,0,0,50,NaT,2025-05-06,inf,2025-09-25,0
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,1,0,1,60,2025-09-03,2025-06-11,84.0,2025-09-16,1
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0,0,0,50,2025-09-03,NaT,inf,2025-10-03,0

In [ ]:
sp_df = pd.read_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\SP Data Load.xlsx')
sp_df = sp_df[['patient_id', 'referral_date', 'prescriber_npi']]
sp_df

      patient_id referral_date  prescriber_npi
0       79540079    2025-08-12    1.073725e+09
1       79540079    2025-08-12    1.073725e+09
2       79540079    2025-08-12    1.073725e+09
3       79540079    2025-08-12    1.073725e+09
4       79540079    2025-08-12    1.073725e+09
...          ...           ...             ...
4155  9982209982    2025-11-06    1.861803e+09
4156  9982209982    2025-11-06    1.861803e+09
4157  9982209982    2025-11-06    1.861803e+09
4158  9982209982    2025-11-06    1.861803e+09
4159  9982209982    2025-11-06    1.861803e+09

[4160 rows x 3 columns]

In [ ]:
df_90 = pd.merge(df_90, sp_df, how='left', left_on=['sp_patient_id', 'sp_prescriber_npi'], right_on=['patient_id', 'prescriber_npi']).drop(columns=['patient_id', 'prescriber_npi'], axis=1)
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date_x,service_date,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date_y
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,0,0,0,50,NaT,NaT,inf,2025-05-13,1,2025-08-04
1,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,0,0,0,50,NaT,NaT,inf,2025-05-13,1,2025-08-04
2,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,0,0,0,50,NaT,NaT,inf,2025-05-13,1,2025-08-04
3,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,0,0,0,50,NaT,NaT,inf,2025-05-13,1,2025-08-04
4,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,0,0,0,50,NaT,NaT,inf,2025-05-13,1,2025-08-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9462,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,0,0,0,50,2025-09-03,NaT,inf,2025-10-03,0,2025-09-03
9463,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,0,0,0,50,2025-09-03,NaT,inf,2025-10-03,0,2025-09-03
9464,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,0,0,0,50,2025-09-03,NaT,inf,2025-10-03,0,2025-09-03
9465,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,0,0,0,50,2025-09-03,NaT,inf,2025-10-03,0,2025-09-03
9466,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,0,0,0,50,2025-09-03,NaT,inf,2025-10-03,0,2025-09-03

In [ ]:
df_90 = df_90.drop_duplicates(subset=['sp_patient_id', 'matched_patient_id'], keep='first').reset_index(drop=True)
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,referral_date_x,service_date,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date_y
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,0,0,0,50,NaT,NaT,inf,2025-05-13,1,2025-08-04
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,0,0,0,55,2025-09-02,NaT,inf,2025-06-04,0,2025-09-02
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,0,0,0,70,2025-09-02,2025-05-20,105.0,2025-09-12,1,2025-09-02
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,0,0,0,70,2025-09-02,2025-05-15,110.0,2025-09-09,0,2025-09-02
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,0,0,0,60,2025-09-02,NaT,inf,2025-10-03,0,2025-09-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,0,0,0,50,NaT,2025-05-06,inf,2025-08-26,0,2025-10-15
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,0,0,0,50,NaT,NaT,inf,2025-10-06,1,2025-10-15
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,0,0,0,50,NaT,2025-05-06,inf,2025-09-25,0,2025-10-15
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,1,0,1,60,2025-09-03,2025-06-11,84.0,2025-09-16,1,2025-09-03
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,0,0,0,50,2025-09-03,NaT,inf,2025-10-03,0,2025-09-03

In [ ]:
df_90['referral_date'] = pd.to_datetime(df_90['referral_date'], errors='coerce')
df_90['latest_service_date'] = pd.to_datetime(df_90['latest_service_date'], errors='coerce')
df_90

KeyError: 'referral_date'

In [ ]:
def generate_days_service_and_referral_lag(row):
    referral_date = row['referral_date']
    service_date = row['latest_service_date']

    if pd.isna(referral_date) or pd.isna(service_date):
        return -1
    
    days_difference = (service_date - referral_date).days

    return abs(days_difference)

df_90['days_service_and_referral_lag'] = df_90.apply(
    generate_days_service_and_referral_lag,
    axis=1
)

In [ ]:
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0,0,0,50,inf,2025-05-13,1,2025-08-04,83
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0,0,0,55,inf,2025-06-04,0,2025-09-02,90
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0,0,0,70,105.0,2025-09-12,1,2025-09-02,10
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0,0,0,70,110.0,2025-09-09,0,2025-09-02,7
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0,0,0,60,inf,2025-10-03,0,2025-09-02,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0,0,0,50,inf,2025-08-26,0,2025-10-15,50
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0,0,0,50,inf,2025-10-06,1,2025-10-15,9
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0,0,0,50,inf,2025-09-25,0,2025-10-15,20
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,1,0,1,60,84.0,2025-09-16,1,2025-09-03,13
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0,0,0,50,inf,2025-10-03,0,2025-09-03,30

In [ ]:
df_90["latest_service_date"] = pd.to_datetime(df_90["latest_service_date"])

max_conf = df_90.groupby("sp_patient_id")["confidence_score"].transform("max")
is_max_conf = df_90["confidence_score"].eq(max_conf)

date_among_max_conf = df_90["latest_service_date"].where(is_max_conf)
max_date = date_among_max_conf.groupby(df_90["sp_patient_id"]).transform("max")
is_max_date = df_90["latest_service_date"].eq(max_date)

is_top2 = is_max_conf & is_max_date

lag_among_top2 = df_90["days_service_and_referral_lag"].where(is_top2, np.inf)
min_lag = lag_among_top2.groupby(df_90["sp_patient_id"]).transform("min")
is_min_lag = df_90["days_service_and_referral_lag"].eq(min_lag)

df_90["best_match_flag"] = (is_top2 & is_min_lag).astype(int)

c:\Users\RuchirTyagi\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\dtypes\cast.py:377: RuntimeWarning: invalid value encountered in cast
  new_result = trans(result).astype(dtype)

In [ ]:
df_90.head()

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0,0,0,50,inf,2025-05-13,1,2025-08-04,83
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0,0,0,55,inf,2025-06-04,0,2025-09-02,90
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0,0,0,70,105.0,2025-09-12,1,2025-09-02,10
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0,0,0,70,110.0,2025-09-09,0,2025-09-02,7
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0,0,0,60,inf,2025-10-03,0,2025-09-02,31

In [ ]:
def generate_payor_flag(row):
    sp_prescriber_npi = row['sp_prescriber_npi']
    sp_patient_id = row['sp_patient_id']
    claims_patient_id = row['matched_patient_id']

    filtered_df = payor_df[(payor_df['sp_prescriber_npi'] == sp_prescriber_npi) & (payor_df['sp_patient_id'] == sp_patient_id) & (payor_df['matched_patient_id'] == claims_patient_id)]

    if filtered_df.empty:
        return None, None, None
    
    return filtered_df['payor_name_final_flag'].iloc[0], filtered_df['payor_type_final_flag'].iloc[0], filtered_df['pbm_final_flag'].iloc[0]

df_90[['payor_name_final_flag', 'payor_type_final_flag', 'pbm_final_flag']] = df_90.apply(
    generate_payor_flag,
    axis=1, 
    result_type='expand'
)

In [ ]:
df_90.to_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\df_90_final_table.xlsx', index=False)

In [ ]:
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0,0,0,50,inf,2025-05-13,1,2025-08-04,83
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0,0,0,55,inf,2025-06-04,0,2025-09-02,90
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0,0,0,70,105.0,2025-09-12,1,2025-09-02,10
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0,0,0,70,110.0,2025-09-09,0,2025-09-02,7
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0,0,0,60,inf,2025-10-03,0,2025-09-02,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0,0,0,50,inf,2025-08-26,0,2025-10-15,50
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0,0,0,50,inf,2025-10-06,1,2025-10-15,9
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0,0,0,50,inf,2025-09-25,0,2025-10-15,20
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0,0,0,60,84.0,2025-09-16,1,2025-09-03,13
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0,0,0,50,inf,2025-10-03,0,2025-09-03,30

In [ ]:
df_90.columns

Index(['sp_prescriber_npi', 'sp_patient_id', 'sp_state', 'sp_gender', 'sp_age',
       'matched_patient_id', 'matched_gender', 'matched_age_2025',
       'matched_state', 'parent_diag_code_flag', 'exact_diag_code_flag',
       'prior_treatment_flag', 'rx_date_match_flag', 'exact_fill_date_flag',
       'lag_fill_date_flag', 'payor_name_final_flag', 'payor_type_final_flag',
       'pbm_final_flag', 'confidence_score', 'diagnosis_days_lag',
       'latest_service_date', 'best_match_flag', 'referral_date',
       'days_service_and_referral_lag'],
      dtype='object')

In [ ]:
new_df = df_90[['sp_prescriber_npi', 'sp_patient_id', 'sp_state', 'sp_gender', 'sp_age',
       'matched_patient_id', 'matched_gender', 'matched_age_2025',
       'matched_state']]

In [ ]:
new_df

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI
...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA

In [ ]:
fill_df = pd.read_csv(r"C:\Users\RuchirTyagi\fill_date_new.csv")
ship_df = pd.read_csv(r"C:\Users\RuchirTyagi\ship_date_new.csv")

fill_df

    patient_id   fill_date
0     KF1RCS7Q  2025-08-28
1     QKPEKY0Z  2025-08-27
2     D79VEXMW  2025-08-31
3     EDYSK4DC  2025-09-07
4     KGWGC445  2025-09-09
..         ...         ...
494   FLEL29W0  2025-08-17
495   JJ0L2D1P  2025-09-20
496   EDYSK4DC  2025-08-18
497   RV08856V  2025-08-13
498   KF1RCS7Q  2025-08-29

[499 rows x 2 columns]

In [ ]:
ship_df.rename(columns={'ship_date.1': 'ship_date'}, inplace=True)

In [ ]:
ship_df['ship_date'] = pd.to_datetime(ship_df['ship_date'], errors='coerce')
fill_df['fill_date'] = pd.to_datetime(fill_df['fill_date'], errors='coerce')

In [ ]:
ship_df.dropna(inplace=True)

In [ ]:
fill_df

    patient_id  fill_date
0     KF1RCS7Q 2025-08-28
1     QKPEKY0Z 2025-08-27
2     D79VEXMW 2025-08-31
3     EDYSK4DC 2025-09-07
4     KGWGC445 2025-09-09
..         ...        ...
494   FLEL29W0 2025-08-17
495   JJ0L2D1P 2025-09-20
496   EDYSK4DC 2025-08-18
497   RV08856V 2025-08-13
498   KF1RCS7Q 2025-08-29

[499 rows x 2 columns]

In [ ]:
new_df = pd.merge(new_df, ship_df, how='left', left_on=['sp_patient_id'], right_on=['patient_id']).drop(columns=['patient_id'], axis=1)
new_df

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,ship_date
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-08-25
1,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-09-29
2,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-10-10
3,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-11-06
4,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,2025-09-12
...,...,...,...,...,...,...,...,...,...,...
2450,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,2025-11-11
2451,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-09-17
2452,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-09-29
2453,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-10-14
2454,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-11-11

In [ ]:
new_df = pd.merge(new_df, fill_df, how='left', left_on='matched_patient_id', right_on='patient_id').drop(columns=['patient_id'], axis=1)
new_df

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,ship_date,fill_date
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-08-25,NaT
1,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-09-29,NaT
2,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-10-10,NaT
3,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-11-06,NaT
4,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,2025-09-12,NaT
...,...,...,...,...,...,...,...,...,...,...,...
3745,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,2025-11-11,NaT
3746,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-09-17,NaT
3747,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-09-29,NaT
3748,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-10-14,NaT
3749,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-11-11,NaT

In [ ]:
referral_df = pd.read_csv(r"C:\Users\RuchirTyagi\referral_date.csv")

In [ ]:
new_df = pd.merge(new_df, referral_df, how='left', left_on=['sp_patient_id', 'matched_patient_id'], right_on=['sp_patient_id', 'matched_patient_id'])
new_df

KeyError: 'sp_patient_id'

In [ ]:
new_df['fill_referral_abs_lag_days'] = (new_df['referral_date'] - new_df['fill_date']).abs().dt.days
new_df['fill_referral_abs_lag_days'] = new_df['fill_referral_abs_lag_days'].fillna(np.inf)
min_lag = new_df.groupby(['sp_patient_id', 'matched_patient_id'])['fill_referral_abs_lag_days'].transform('min')
new_df['closest_fill_to_referral_flag'] = (new_df['fill_referral_abs_lag_days'] == min_lag).astype(int)
new_df

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,ship_date,fill_date,referral_date,fill_referral_abs_lag_days,closest_fill_to_referral_flag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-11-03,NaT,2025-08-04,inf,1
1,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-11-18,NaT,2025-08-04,inf,1
2,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-09-10,NaT,2025-08-04,inf,1
3,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-09-30,NaT,2025-08-04,inf,1
4,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,2025-10-22,NaT,2025-08-04,inf,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4644,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-11-25,NaT,2025-09-03,inf,1
4645,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-09-08,NaT,2025-09-03,inf,1
4646,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-10-03,NaT,2025-09-03,inf,1
4647,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-11-03,NaT,2025-09-03,inf,1
4648,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,2025-09-17,NaT,2025-09-03,inf,1

In [ ]:
new_df = new_df[(new_df['fill_referral_abs_lag_days'] != np.inf) & (new_df['closest_fill_to_referral_flag'] == 1) & (new_df['ship_date'].notna()) & (new_df['fill_date'].notna())]

In [ ]:
new_df = new_df.drop_duplicates(subset=['sp_patient_id', 'matched_patient_id'], keep='first').reset_index(drop=True)
new_df

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,ship_date,fill_date,referral_date,fill_referral_abs_lag_days,closest_fill_to_referral_flag
0,1023215944,880080880,VA,M,9,D79VEXMW,M,10,VA,2025-09-19,2025-08-29,2025-08-28,1.0,1
1,1023319761,1280051280,MA,F,6,7BSJL5W4,F,7,MA,2025-10-22,2025-08-28,2025-08-28,0.0,1
2,1144099078,2480082480,CA,M,16,7B9SS7JG,M,17,CA,2025-10-17,2025-08-29,2025-08-28,1.0,1
3,1184853814,2479292479,PA,M,5,01SLEM3L,M,5,PA,2025-10-01,2025-08-28,2025-08-04,24.0,1
4,1225276942,2480212480,NJ,M,50,GBJGWY3T,M,50,NJ,2025-10-17,2025-09-04,2025-09-04,0.0,1
5,1225337017,280820280,IL,M,56,TCZVBMGS,M,56,IL,2025-09-25,2025-09-23,2025-09-23,0.0,1
6,1225337017,979290979,IL,M,40,FLEL29W0,M,41,IL,2025-11-17,2025-08-14,2025-08-04,10.0,1
7,1336307818,1879501879,NY,F,23,RZ2YC5VN,F,23,NY,2025-11-25,2025-08-13,2025-08-11,2.0,1
8,1578679775,1180661180,WA,F,26,XL1Y4EML,F,27,WA,2025-09-03,2025-09-18,2025-09-17,1.0,1
9,1578819827,280150280,CO,M,42,KKCCT07P,M,42,CO,2025-10-02,2025-09-02,2025-09-02,0.0,1
10,1578819827,1679211679,UT,M,20,RV08856V,M,20,UT,2025-11-04,2025-08-13,2025-07-31,13.0,1
11,1588857718,1679291679,IL,M,6,HZ0R5B80,M,6,IL,2025-09-02,2025-10-07,2025-08-04,64.0,1
12,1649410036,2879292879,IL,F,64,WB9S2M5N,F,64,IL,2025-10-08,2025-08-15,2025-08-04,11.0,1
13,1649535857,1780651780,OH,F,25,ZLVPX01X,F,25,OH,2025-10-16,2025-09-17,2025-09-17,0.0,1
14,1689830465,2679502679,WI,F,14,G1CSPNGW,F,14,WI,2025-09-09,2025-10-02,2025-08-11,52.0,1
15,1720291727,1379551379,NJ,F,60,PGFVXJPH,F,60,NJ,2025-10-15,2025-08-14,2025-08-13,1.0,1
16,1821265232,1379731379,MD,M,52,VYJ4PXJD,M,52,MD,2025-09-05,2025-08-20,2025-08-18,2.0,1
17,1831275205,1971921971,OH,M,36,PSSV1SH4,M,36,OH,2025-11-10,2025-08-21,2025-08-21,0.0,1
18,1871580118,980830980,FL,M,6,2WG17ESZ,M,7,FL,2025-11-17,2025-09-23,2025-09-23,0.0,1
19,1871804823,2381122381,TX,F,8,D9XLDWNH,F,8,TX,2025-09-08,2025-10-02,2025-10-02,0.0,1
20,1891827465,180030180,FL,F,71,KF1RCS7Q,F,72,FL,2025-11-05,2025-08-27,2025-08-27,0.0,1
21,1922428333,279830279,PA,M,60,BFZHF237,M,60,PA,2025-10-28,2025-08-21,2025-08-21,0.0,1
22,1952797664,2579952579,OH,M,5,MKV06TCM,M,5,OH,2025-09-04,2025-08-26,2025-08-26,0.0,1

In [ ]:
new_df.drop(columns=['fill_referral_abs_lag_days', 'closest_fill_to_referral_flag'], axis=1, inplace=True)
new_df

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,ship_date,fill_date,referral_date
0,1023215944,880080880,VA,M,9,D79VEXMW,M,10,VA,2025-09-19,2025-08-29,2025-08-28
1,1023319761,1280051280,MA,F,6,7BSJL5W4,F,7,MA,2025-10-22,2025-08-28,2025-08-28
2,1144099078,2480082480,CA,M,16,7B9SS7JG,M,17,CA,2025-10-17,2025-08-29,2025-08-28
3,1184853814,2479292479,PA,M,5,01SLEM3L,M,5,PA,2025-10-01,2025-08-28,2025-08-04
4,1225276942,2480212480,NJ,M,50,GBJGWY3T,M,50,NJ,2025-10-17,2025-09-04,2025-09-04
5,1225337017,280820280,IL,M,56,TCZVBMGS,M,56,IL,2025-09-25,2025-09-23,2025-09-23
6,1225337017,979290979,IL,M,40,FLEL29W0,M,41,IL,2025-11-17,2025-08-14,2025-08-04
7,1336307818,1879501879,NY,F,23,RZ2YC5VN,F,23,NY,2025-11-25,2025-08-13,2025-08-11
8,1578679775,1180661180,WA,F,26,XL1Y4EML,F,27,WA,2025-09-03,2025-09-18,2025-09-17
9,1578819827,280150280,CO,M,42,KKCCT07P,M,42,CO,2025-10-02,2025-09-02,2025-09-02
10,1578819827,1679211679,UT,M,20,RV08856V,M,20,UT,2025-11-04,2025-08-13,2025-07-31
11,1588857718,1679291679,IL,M,6,HZ0R5B80,M,6,IL,2025-09-02,2025-10-07,2025-08-04
12,1649410036,2879292879,IL,F,64,WB9S2M5N,F,64,IL,2025-10-08,2025-08-15,2025-08-04
13,1649535857,1780651780,OH,F,25,ZLVPX01X,F,25,OH,2025-10-16,2025-09-17,2025-09-17
14,1689830465,2679502679,WI,F,14,G1CSPNGW,F,14,WI,2025-09-09,2025-10-02,2025-08-11
15,1720291727,1379551379,NJ,F,60,PGFVXJPH,F,60,NJ,2025-10-15,2025-08-14,2025-08-13
16,1821265232,1379731379,MD,M,52,VYJ4PXJD,M,52,MD,2025-09-05,2025-08-20,2025-08-18
17,1831275205,1971921971,OH,M,36,PSSV1SH4,M,36,OH,2025-11-10,2025-08-21,2025-08-21
18,1871580118,980830980,FL,M,6,2WG17ESZ,M,7,FL,2025-11-17,2025-09-23,2025-09-23
19,1871804823,2381122381,TX,F,8,D9XLDWNH,F,8,TX,2025-09-08,2025-10-02,2025-10-02
20,1891827465,180030180,FL,F,71,KF1RCS7Q,F,72,FL,2025-11-05,2025-08-27,2025-08-27
21,1922428333,279830279,PA,M,60,BFZHF237,M,60,PA,2025-10-28,2025-08-21,2025-08-21
22,1952797664,2579952579,OH,M,5,MKV06TCM,M,5,OH,2025-09-04,2025-08-26,2025-08-26

In [ ]:
def generate_days_fill_ship(row):
    fill_date = row['fill_date']
    ship_date = row['ship_date']

    if pd.isna(fill_date) or pd.isna(ship_date):
        return -1

    days_lag = (ship_date - fill_date).days

    return abs(days_lag)

new_df['days_fill_and_ship_lag'] = new_df.apply(
    generate_days_fill_ship,
    axis=1
)

In [ ]:
new_df

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,ship_date,fill_date,referral_date,days_fill_and_ship_lag
0,1023215944,880080880,VA,M,9,D79VEXMW,M,10,VA,2025-09-19,2025-08-29,2025-08-28,21
1,1023319761,1280051280,MA,F,6,7BSJL5W4,F,7,MA,2025-10-22,2025-08-28,2025-08-28,55
2,1144099078,2480082480,CA,M,16,7B9SS7JG,M,17,CA,2025-10-17,2025-08-29,2025-08-28,49
3,1184853814,2479292479,PA,M,5,01SLEM3L,M,5,PA,2025-10-01,2025-08-28,2025-08-04,34
4,1225276942,2480212480,NJ,M,50,GBJGWY3T,M,50,NJ,2025-10-17,2025-09-04,2025-09-04,43
5,1225337017,280820280,IL,M,56,TCZVBMGS,M,56,IL,2025-09-25,2025-09-23,2025-09-23,2
6,1225337017,979290979,IL,M,40,FLEL29W0,M,41,IL,2025-11-17,2025-08-14,2025-08-04,95
7,1336307818,1879501879,NY,F,23,RZ2YC5VN,F,23,NY,2025-11-25,2025-08-13,2025-08-11,104
8,1578679775,1180661180,WA,F,26,XL1Y4EML,F,27,WA,2025-09-03,2025-09-18,2025-09-17,15
9,1578819827,280150280,CO,M,42,KKCCT07P,M,42,CO,2025-10-02,2025-09-02,2025-09-02,30
10,1578819827,1679211679,UT,M,20,RV08856V,M,20,UT,2025-11-04,2025-08-13,2025-07-31,83
11,1588857718,1679291679,IL,M,6,HZ0R5B80,M,6,IL,2025-09-02,2025-10-07,2025-08-04,35
12,1649410036,2879292879,IL,F,64,WB9S2M5N,F,64,IL,2025-10-08,2025-08-15,2025-08-04,54
13,1649535857,1780651780,OH,F,25,ZLVPX01X,F,25,OH,2025-10-16,2025-09-17,2025-09-17,29
14,1689830465,2679502679,WI,F,14,G1CSPNGW,F,14,WI,2025-09-09,2025-10-02,2025-08-11,23
15,1720291727,1379551379,NJ,F,60,PGFVXJPH,F,60,NJ,2025-10-15,2025-08-14,2025-08-13,62
16,1821265232,1379731379,MD,M,52,VYJ4PXJD,M,52,MD,2025-09-05,2025-08-20,2025-08-18,16
17,1831275205,1971921971,OH,M,36,PSSV1SH4,M,36,OH,2025-11-10,2025-08-21,2025-08-21,81
18,1871580118,980830980,FL,M,6,2WG17ESZ,M,7,FL,2025-11-17,2025-09-23,2025-09-23,55
19,1871804823,2381122381,TX,F,8,D9XLDWNH,F,8,TX,2025-09-08,2025-10-02,2025-10-02,24
20,1891827465,180030180,FL,F,71,KF1RCS7Q,F,72,FL,2025-11-05,2025-08-27,2025-08-27,70
21,1922428333,279830279,PA,M,60,BFZHF237,M,60,PA,2025-10-28,2025-08-21,2025-08-21,68
22,1952797664,2579952579,OH,M,5,MKV06TCM,M,5,OH,2025-09-04,2025-08-26,2025-08-26,9

In [ ]:
new_df.to_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\df_90_final_table_fill_ship_lag.xlsx', index=False)

In [ ]:
def generate_confidence_score(row):
    parent_diag_code_flag = row['parent_diag_code_flag']
    exact_diag_code_flag = row['exact_diag_code_flag']
    prior_treatment_flag = row['prior_treatment_flag']
    rx_date_match_flag = row['rx_date_match_flag']
    lag_fill_date_flag = row['lag_fill_date_flag']
    payor_name_final_flag = row['payor_name_final_flag']
    payor_type_final_flag = row['payor_type_final_flag']
    pbm_final_flag = row['pbm_final_flag']

    diagnosis_score_parent = 0
    diagnosis_score_exact = 0

    if parent_diag_code_flag == 1:
        diagnosis_score_parent = 5
    
    if exact_diag_code_flag == 1:
        diagnosis_score_exact = 5

    final_dispense = 0

    if rx_date_match_flag == 1:
        if lag_fill_date_flag == 1 or lag_fill_date_flag == -1:
            final_dispense = 20

    therapy_score = 0

    if prior_treatment_flag == 1:
        therapy_score = 10

    payor_type_score = 0
    payor_name_score = 0
    pbm_score = 0

    if payor_name_final_flag == 1:
        payor_name_score = 2

    if payor_type_final_flag == 1:
        payor_type_score = 5 

    if pbm_final_flag == 1:
        pbm_score = 3

    confidence_score = diagnosis_score_parent + diagnosis_score_exact + final_dispense + therapy_score + payor_type_score + payor_name_score + pbm_score + 50

    return confidence_score

In [ ]:
df_90['confidence_score'] = df_90.apply(
    generate_confidence_score,
    axis=1
)

df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0,0,0,50,-1,2025-05-13,1,2025-08-04,83
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0,0,0,55,245,2025-06-04,0,2025-09-02,90
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0,0,0,70,27,2025-09-12,1,2025-09-02,10
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0,0,0,70,61,2025-09-09,0,2025-09-02,7
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0,0,0,60,189,2025-10-03,0,2025-09-02,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0,0,0,50,-1,2025-08-26,0,2025-10-15,50
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0,0,0,50,-1,2025-10-06,1,2025-10-15,9
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0,0,0,50,-1,2025-09-25,0,2025-10-15,20
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0,0,0,60,21,2025-09-16,1,2025-09-03,13
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0,0,0,50,-1,2025-10-03,0,2025-09-03,30

In [ ]:
df_90["latest_service_date"] = pd.to_datetime(df_90["latest_service_date"])

max_conf = df_90.groupby("sp_patient_id")["confidence_score"].transform("max")
is_max_conf = df_90["confidence_score"].eq(max_conf)

date_among_max_conf = df_90["latest_service_date"].where(is_max_conf)
max_date = date_among_max_conf.groupby(df_90["sp_patient_id"]).transform("max")
is_max_date = df_90["latest_service_date"].eq(max_date)

is_top2 = is_max_conf & is_max_date

lag_among_top2 = df_90["days_service_and_referral_lag"].where(is_top2, np.inf)
min_lag = lag_among_top2.groupby(df_90["sp_patient_id"]).transform("min")
is_min_lag = df_90["days_service_and_referral_lag"].eq(min_lag)

df_90["best_match_flag"] = (is_top2 & is_min_lag).astype(int)

c:\Users\RuchirTyagi\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\dtypes\cast.py:377: RuntimeWarning: invalid value encountered in cast
  new_result = trans(result).astype(dtype)

In [ ]:
df_90.to_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\df_90_output.xlsx', index=False)

In [ ]:
df_90[df_90['confidence_score'] >= 70].shape

(106, 24)

In [ ]:
best_match = df_90[df_90['best_match_flag'] == 1]

In [ ]:
df_90[df_90['sp_patient_id'] == 5679885679]

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
143,1164717369,5679885679,PA,F,47,14STPYFS,F,46,PA,1.0,...,-1.0,0,0,0,60,4,2025-09-10,0,2025-08-22,19
144,1164717369,5679885679,PA,F,47,61XKL7Q9,F,48,PA,1.0,...,-1.0,0,0,0,70,66,2025-08-01,0,2025-08-22,21
145,1164717369,5679885679,PA,F,47,BPEN4241,F,47,PA,1.0,...,1.0,0,0,0,60,70,2025-09-25,0,2025-08-22,34
146,1164717369,5679885679,PA,F,47,YXHGZGGC,F,46,PA,1.0,...,-1.0,0,0,0,70,28,2025-09-19,1,2025-08-22,28

In [ ]:
best_match.to_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\best_match_output.xlsx', index=False)

In [ ]:
all_id_df = pd.read_csv(r'C:\Users\RuchirTyagi\all_modeyso_claim_patients.csv')
all_id_df

   patient_id
0    01SLEM3L
1    0MH1V7JH
2    1BWZ1QLR
3    1F7ML962
4    2WG17ESZ
..        ...
82   YK0VQYN4
83   YWX6W4NW
84   ZB1X8TEE
85   ZLVPX01X
86   ZY23WCRV

[87 rows x 1 columns]

In [ ]:
for id in all_id_df['patient_id'].to_list():
    if id not in df_90['matched_patient_id'].to_list():
        print(id)

JM5WCTFN
LB4QYFKZ

In [ ]:
import pandas as pd

fd_4 = pd.read_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\final_table_v4.xlsx')
fd_4

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,icd_code,...,days_supply_final_flag,quantity_final_flag,rx_written_date,fill_date,ship_date,date_prescription_written,prior_treatment_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag
0,1003101056,9279339279,MA,F,64,9MZ6V2LE,F,64,MA,C719,...,1,1,"[Timestamp('2025-08-05 00:00:00'), Timestamp('...","[Timestamp('2025-08-21 00:00:00'), Timestamp('...","[Timestamp('2025-08-22 00:00:00'), Timestamp('...","[Timestamp('2025-08-05 00:00:00'), Timestamp('...",-1,0,0,0
1,1003101056,9279339279,MA,F,64,0XSZNET0,F,63,MA,C719,...,-1,-1,"[Timestamp('2025-08-05 00:00:00'), Timestamp('...",[],"[Timestamp('2025-08-22 00:00:00'), Timestamp('...",[],-1,0,0,0
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,C719,...,-1,-1,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],1,0,0,0
3,1003221896,5280135280,WI,M,5,Y57KB31F,M,4,WI,C719,...,-1,-1,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],1,0,0,0
4,1003221896,5280135280,WI,M,5,2XJVDDQ4,M,4,WI,C719,...,-1,-1,"[Timestamp('2025-09-02 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-12 00:00:00'), Timestamp('...",[],1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2201,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,C719,...,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],-1,0,0,0
2202,1992401996,1880171880,VA,M,12,S9E2PSB7,M,13,VA,C719,...,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],-1,0,0,0
2203,1992401996,1880171880,VA,M,12,38B8371E,M,13,VA,C719,...,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],-1,0,0,0
2204,1992401996,1880171880,VA,M,12,JJSW263R,M,13,VA,C719,...,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],-1,0,0,1
2205,1992401996,1880171880,VA,M,12,H2J20RG9,M,13,VA,C719,...,-1,-1,"[Timestamp('2025-09-03 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-17 00:00:00'), Timestamp('...",[],-1,0,0,0

In [ ]:
fd_4[fd_4['matched_patient_id'] == 'FJ6TLDVQ']

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,icd_code,...,days_supply_final_flag,quantity_final_flag,rx_written_date,fill_date,ship_date,date_prescription_written,prior_treatment_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag
411,1194784231,6779126779,AR,F,22,FJ6TLDVQ,F,22,AR,C719,...,-1,-1,"[Timestamp('2025-07-29 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-04 00:00:00'), Timestamp('...",[],-1,0,0,0
2177,1982903126,6779126779,AR,F,22,FJ6TLDVQ,F,22,AR,C719,...,-1,-1,"[Timestamp('2025-07-29 00:00:00'), Timestamp('...",[],"[Timestamp('2025-09-04 00:00:00'), Timestamp('...",[],-1,0,0,0

In [ ]:
bm = pd.read_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\best_match_output.xlsx')
bm

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1,...,-1,0,0,0,50,-1,2025-05-13,1,2025-08-04,83
1,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1,...,-1,0,0,0,75,27,2025-09-12,1,2025-09-02,10
2,1003349028,7880807880,IL,F,23,0YSEZ8KH,F,23,IL,1,...,-1,0,0,0,65,92,2025-08-22,1,2025-09-23,32
3,1003349028,8781638781,IL,F,24,0YSEZ8KH,F,23,IL,1,...,-1,0,0,0,65,119,2025-08-22,1,2025-10-20,59
4,1003606146,3582653582,WA,M,23,K7V9CEZ9,M,23,WA,1,...,-1,0,0,0,65,49,2025-10-02,1,2025-11-19,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,1972547560,3680363680,VA,M,16,WW6H7EV9,M,16,VA,1,...,-1,0,0,1,68,113,2025-09-29,1,2025-09-09,20
293,1972776623,3180333180,CA,M,28,YWX6W4NW,M,29,CA,1,...,-1,0,0,0,75,346,2025-09-19,1,2025-09-08,11
294,1982686622,2282122282,CT,M,22,KJP330PF,M,22,CT,1,...,-1,0,1,1,73,77,2025-09-12,1,2025-11-04,53
295,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1,...,-1,0,0,0,50,-1,2025-10-06,1,2025-10-15,9
296,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1,...,-1,0,0,0,65,21,2025-09-16,1,2025-09-03,13

In [ ]:
fd_4[fd_4['matched_patient_id'] == 'P9G27ZG0']

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,icd_code,...,prior_chemotherapy_treatment_flag,prior_surgery_treatment_flag,rx_date_match_flag,exact_fill_date_flag,lag_fill_date_flag,days_supply_final_flag,quantity_final_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag
1737,1801180773,5481065481,NH,M,13,P9G27ZG0,M,14,NH,C719,...,-1,-1,-1,-1,-1,-1,-1,0,0,0

In [ ]:
bm[bm['matched_patient_id'] == 'P9G27ZG0']

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
236,1801180773,5481065481,NH,M,13,P9G27ZG0,M,14,NH,1,...,-1,0,0,0,65,1,2025-08-13,1,2025-10-01,49

In [ ]:
temp = pd.read_excel(r'C:\Users\RuchirTyagi\OneDrive - ProcDNA Analytics Pvt. Ltd\Documents\Internal\Data Stitching\final_table_v4.xlsx')

In [ ]:
temp[temp['matched_patient_id'] == 'C7WPDV4S']['lag_fill_date_flag']

1369    1
2112    1
Name: lag_fill_date_flag, dtype: int64

In [ ]:
temp[(temp['sp_patient_id'] == 7979337979) & (temp['matched_patient_id'] == '90M7N6LF')].iloc[:,30:]

,exact_fill_date_flag,lag_fill_date_flag,days_supply_final_flag,quantity_final_flag,rx_written_date,fill_date,ship_date,date_prescription_written,payor_name_final_flag,payor_type_final_flag,pbm_final_flag
90,0,0,0,0,"[Timestamp('2025-08-05 00:00:00'), Timestamp('...","[Timestamp('2025-09-23 00:00:00'), Timestamp('...","[Timestamp('2025-09-03 00:00:00'), Timestamp('...","[Timestamp('2025-09-23 00:00:00'), Timestamp('...",0,0,0
577,0,0,0,0,"[Timestamp('2025-08-05 00:00:00'), Timestamp('...","[Timestamp('2025-09-23 00:00:00'), Timestamp('...","[Timestamp('2025-09-03 00:00:00'), Timestamp('...","[Timestamp('2025-09-23 00:00:00'), Timestamp('...",0,0,0
1885,0,0,0,0,"[Timestamp('2025-08-05 00:00:00'), Timestamp('...","[Timestamp('2025-09-23 00:00:00'), Timestamp('...","[Timestamp('2025-09-03 00:00:00'), Timestamp('...","[Timestamp('2025-09-23 00:00:00'), Timestamp('...",0,0,0

In [ ]:
df_90

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
0,1003221896,2579292579,WI,M,8,H0S6CJSK,M,7,WI,-1.0,...,-1.0,0,0,0,50,-1,2025-05-13,1,2025-08-04,83
1,1003221896,5280135280,WI,M,5,843DX0KF,M,5,WI,1.0,...,-1.0,0,0,0,55,245,2025-06-04,0,2025-09-02,90
2,1003221896,5280135280,WI,M,5,88ZFPLSE,M,5,WI,1.0,...,-1.0,0,0,0,70,27,2025-09-12,1,2025-09-02,10
3,1003221896,5280135280,WI,M,5,H2S3566S,M,6,WI,1.0,...,-1.0,0,0,0,70,61,2025-09-09,0,2025-09-02,7
4,1003221896,5280135280,WI,M,5,VMDGVRH6,M,4,WI,1.0,...,-1.0,0,0,0,60,189,2025-10-03,0,2025-09-02,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,1982903126,9681529681,TX,F,14,KHP2NC7M,F,14,TX,-1.0,...,-1.0,0,0,0,50,-1,2025-08-26,0,2025-10-15,50
904,1982903126,9681529681,TX,F,14,Q82R8LBC,F,14,TX,-1.0,...,-1.0,0,0,0,50,-1,2025-10-06,1,2025-10-15,9
905,1982903126,9681529681,TX,F,14,TW1WHTTM,F,13,TX,-1.0,...,-1.0,0,0,0,50,-1,2025-09-25,0,2025-10-15,20
906,1992401996,1880171880,VA,M,12,06R2J3C9,M,13,VA,1.0,...,-1.0,0,0,0,60,21,2025-09-16,1,2025-09-03,13
907,1992401996,1880171880,VA,M,12,H987GVYY,M,12,VA,-1.0,...,-1.0,0,0,0,50,-1,2025-10-03,0,2025-09-03,30

In [ ]:
df_90[df_90['sp_patient_id'] == 7979337979]

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
47,1043765977,7979337979,CA,F,34,90M7N6LF,F,34,CA,1.0,...,0.0,0,0,0,60,47,2025-10-07,1,2025-08-06,62
48,1043765977,7979337979,CA,F,34,CPQS7TV6,F,34,CA,1.0,...,-1.0,0,0,0,60,54,2025-10-07,1,2025-08-06,62
806,1871754655,7979337979,CA,F,34,3SWH575W,F,35,CA,-1.0,...,-1.0,0,0,0,50,-1,2025-09-15,0,2025-08-06,40

In [ ]:
df_90[df_90['matched_patient_id'] == 'K364WFHG']

,sp_prescriber_npi,sp_patient_id,sp_state,sp_gender,sp_age,matched_patient_id,matched_gender,matched_age_2025,matched_state,parent_diag_code_flag,...,lag_fill_date_flag,payor_name_final_flag,payor_type_final_flag,pbm_final_flag,confidence_score,diagnosis_days_lag,latest_service_date,best_match_flag,referral_date,days_service_and_referral_lag
263,1295566057,8381228381,CA,F,35,K364WFHG,F,36,CA,-1.0,...,1.0,0,0,0,50,-1,2025-10-03,1,2025-10-07,4